Repository SSARY-ssafy/APP, pull requests merged in 2024-12, with the labels that each got.

#15 새 글 & 기존 글 UI/UX 변경
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ssary/MyExistTextActivity.java
  app/src/main/java/com/example/ssary/MyNewTextActivity.java
  app/src/main/res/drawable/ic_attach.png
  app/src/main/res/drawable/ic_bold.png
  app/src/main/res/drawable/ic_delete.png
  app/src/main/res/drawable/ic_download.png
  app/src/main/res/drawable/ic_edit.png
  app/src/main/res/drawable/ic_folder_open.png
  app/src/main/res/drawable/ic_folderopen.png
  app/src/main/res/drawable/ic_image.png
  app/src/main/res/drawable/ic_italic.png
  app/src/main/res/drawable/ic_profile.png
  app/src/main/res/drawable/ic_strikethrough.png
  app/src/main/res/drawable/ic_underline.png
  app/src/main/res/layout/activity_my_exist_text.xml
  app/src/main/res/layout/activity_my_new_text.xml
  app/src/main/res/layout/activity_my_page.xml
Labels: feat

#21 멀티파일 기능 구현
  app/src/main/java/com/example/ssary/MyExistTextActivity.java
  app/src/main/java/com/example/ssary/MyNewTextActivity.java
  app/src/main/res/drawable/ic_edit.png
  app/src/main/res/layout/activity_my_exist_text.xml
  app/src/main/res/layout/activity_my_new_text.xml
  app/src/main/res/layout/my_exist_text_uploaded_file.xml
  app/src/main/res/layout/my_new_text_uploaded_file.xml
Labels: feat

#22 채용공고 페이지 수정 / job_item_layout 수정 (채용중/마감) / 데이터 변경 / activity_job 레이아…
  app/src/main/java/com/example/ssary/JobActivity.java
  app/src/main/java/com/example/ssary/JobsAdapter.java
  app/src/main/res/drawable/company_item_background.xml
  app/src/main/res/layout/activity_job.xml
Labels: feat

#23 [Feat]카테고리별 색상 설정 기능 추가
  app/src/main/java/com/example/ssary/MyPageActivity.java
  app/src/main/res/layout/activity_my_page.xml
Labels: feat

#25 Yoonjune
  .idea/deploymentTargetSelector.xml
  .idea/inspectionProfiles/Project_Default.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ssary/CalendarActivity.java
  app/src/main/java/com/example/ssary/MainActivity.java
  app/src/main/res/drawable/dialog_background.xml
  app/src/main/res/drawable/edittext_border.xml
  app/src/main/res/drawable/grid_border.xml
  app/src/main/res/drawable/ic_arrow_left.png
  app/src/main/res/drawable/ic_arrow_right.png
  app/src/main/res/drawable/ic_back.png
  app/src/main/res/drawable/ic_plus_button.png
  app/src/main/res/drawable/line_divider.xml
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_add_schedule.xml
  app/src/main/res/layout/dialog_schedule_list.xml
  app/src/main/res/layout/item_schedule.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: feat

#28 파일 CRUD 프로세스 버그 해결
  app/src/main/java/com/example/ssary/MyExistTextActivity.java
  app/src/main/java/com/example/ssary/MyNewTextActivity.java
Labels: bug, feat

#30 company_info 표시 레이아웃 변경
  app/src/main/java/com/example/ssary/Job.java
  app/src/main/java/com/example/ssary/JobActivity.java
  app/src/main/res/layout/company_info.xml
Labels: feat

#33 게시글 삭제 기능 보완 및 카테고리 수정 기능 추가
  app/src/main/java/com/example/ssary/MyExistTextActivity.java
  app/src/main/java/com/example/ssary/MyNewTextActivity.java
  app/src/main/res/layout/activity_my_exist_text.xml
Labels: feat

#34 마이 캘린더 페이지 내 채용공고 추가
  app/src/main/java/com/example/ssary/CalendarActivity.java
  app/src/main/res/layout/dialog_schedule_list.xml
  app/src/main/res/layout/item_job.xml
Labels: enhancement

#35 파일 업로드 속도 개선
  app/src/main/java/com/example/ssary/MyExistTextActivity.java
  app/src/main/java/com/example/ssary/MyNewTextActivity.java
Labels: enhancement

#36 캘린더 일정 CRUD 완성
  app/src/main/java/com/example/ssary/CalendarActivity.java
  app/src/main/res/layout/dialog_schedule_list.xml
  app/src/main/res/layout/item_schedule.xml
Labels: feat

#37 [Feat] 전체 카테고리에서 글 보기, 카테고리별 색상 변경, 카테고리별 기능들 메뉴로 통합
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/ssary/MyPageActivity.java
  app/src/main/res/drawable/ic_menu.png
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/menu/category_menu.xml
Labels: enhancement, feat
