Repository SSARY-ssafy/APP, pull requests merged in 2025-01, with the labels that each got.

#38 메인페이지 - 채용공고 수정
  app/src/main/java/com/example/ssary/MainActivity.java
  app/src/main/java/com/example/ssary/MainJobAdapter.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_job_page.xml
Labels: enhancement

#40 bug: Ellipsis Truncation
  app/src/main/java/com/example/ssary/MyExistTextActivity.java
  app/src/main/java/com/example/ssary/MyNewTextActivity.java
Labels: bug

#41 이미지 삽입 기능
  app/build.gradle.kts
  app/src/main/java/com/example/ssary/MyExistTextActivity.java
  app/src/main/java/com/example/ssary/MyNewTextActivity.java
  app/src/main/java/com/example/ssary/ui/theme/UndoRedoManager.java
  app/src/main/res/drawable/ic_redo.png
  app/src/main/res/drawable/ic_undo.png
  app/src/main/res/layout/activity_my_exist_text.xml
  app/src/main/res/layout/activity_my_new_text.xml
Labels: bug, feat

#42 이미지 삽입 추가 기능 (ver2)
  app/src/main/java/com/example/ssary/MyExistTextActivity.java
  app/src/main/java/com/example/ssary/MyNewTextActivity.java
  app/src/main/java/com/example/ssary/ui/theme/UndoRedoManager.java
Labels: bug, feat

#43 이미지 삽입 기능 완료
  app/src/main/java/com/example/ssary/MyExistTextActivity.java
Labels: bug

#45 메인페이지 캘린더 영역 완료
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/ssary/MainActivity.java
  app/src/main/res/drawable/bg_shape_no_padding.xml
  app/src/main/res/drawable/circle_background.xml
  app/src/main/res/drawable/square_blue.xml
  app/src/main/res/layout/activity_main.xml
Labels: feat

#46 이미지 삽입 기능 버그 해결
  app/src/main/java/com/example/ssary/MyExistTextActivity.java
  app/src/main/java/com/example/ssary/MyNewTextActivity.java
  app/src/main/java/com/example/ssary/ui/theme/UndoRedoManager.java
Labels: bug, feat
